### PR TITLE
REMOVE: ?rel=0 from YouTube iframe URLs so that users can more easily…

### LINKED ISSUE #7: Is there an option to open the youtube vid in a new window?

### PR DESCRIPTION
**Pull request by dwgreen1**
… pop out the video into a new window or tab

Closes #7

### CODE REVIEW

**Comment by kenirwin** [comment]
@dwgreen1 - is there a way to test this that you'd suggest?

**Comment by dwgreen1** [comment]
Since all of last year's YouTube videos are now removed, and since we do not have any new ones in place of them yet, I can only suggest that someone:

1. Pull this branch locally
2. Add an arbitrary YouTube video to a conference session (for testing)
3. Run Jekyll serve
4. Navigate to your test session and observe the YouTube video and options

If the test is successful, then this can be merged; just be sure that no changes were pushed back.

**Comment by kenirwin** [comment]
@dwgreen1 - I'm not sure what the behavior change I should be seeing is -- the videos load inline, so I'm not sure where the option to open as a new tab is. I wonder if I'm looking at the wrong part of the interface?

**Comment by dwgreen1** [comment]
@kenirwin - Take a look back on my comment for #7 

In the screenshot I added, there is the option to "Watch on YouTube", which opens the video in a new tab. Do you see the same thing as you are testing? If you don't, then I wonder if it's dependent on the browser, and we will have to take another look at it or find another solution.

**Comment by kenirwin** [comment]
That works -- we may also want to consider having plain-old-link to the video and not just a feature of the embedded media file.

**Pull request merged**
