### PR TITLE
Update Sofia's bio

### PR DESCRIPTION
**Pull request by kenirwin**
update Sofia's description from text she sent to Jess

### CODE REVIEW

**Comment by dwgreen1** [comment]
Ken, it looks like most of the URLs in her bio are wrapped in a https://urldefense.com URL rather than the direct URL itself. Was that intentional? Or maybe it snuck its way in from copy/paste from an email?

**Comment by kenirwin** [comment]
I did leave the urldefense in on purpose -- I don't know what the reason for that prefix is, but that's how Sofia sent it to us, and the link works. I know that she has some privacy concerns, and I thought this might be related. If it's just something that gets added to the emails some people send and receive, then maybe it makes sense to remove it.

**Comment by kenirwin** [comment]
@dwgreen1 -- I've fixed the urls

**Comment by dwgreen1** [comment]
@kenirwin, is there a URL we need to use for the [ACRL Immersion Program](https://www.ala.org/acrl/conferences/immersion)? I see this one, but it might be a confusing hyperlink. Or do we want to remove it altogether?

**Comment by kenirwin** [comment]
Good point @dwgreen1 -- the available link is confusing and out of date, at least for now. I've removed it; ready to merge?

**Pull request merged**
